### ISSUE TITLE
Create .gitignore with useful content

### ISSUE THREAD

**Issue by janpio** [apache/cordova-app-hello-world#30]
The file https://github.com/apache/cordova-app-hello-world/blob/master/template_src/.gitignore exists, but it is not created when using `cordova create`:

![image](https://user-images.githubusercontent.com/183673/48959772-f2dc6480-ef67-11e8-898e-3eb9d3b1f2c5.png)

**Comment by brodybits** [comment]
Basically the same as <https://issues.apache.org/jira/browse/CB-12397>, due to npm behavior discussed in <https://github.com/apache/cordova-create/pull/8>, where I had already proposed a workaround solution. (`npm` turns `.gitignore` into `.npmignore` as you can see in the screenshot above)

More info coming, maybe later this weekend. There seems to be some unfinished work discussed in https://github.com/apache/cordova-create/pull/8>, <https://github.com/apache/cordova-create/pull/14>, hello-world #22, and apache/cordova-discuss#69 (I still don't favor using `_gitignore` for reasons I said before).

**Comment by janpio** [comment]
When we solved this, also push it to repos collecting default gitignores like https://github.com/github/gitignore and https://github.com/dvcs/gitignore

**Comment by raphinesse** [comment]
A useful `.gitignore` is created by `cordova-create@nightly`
